name : repository_mirroring
on :
  push :
    branches :
      - main
env :
  TARGET_REPO_URL : git@github.com:EpitechPromo2028/B-DOP-200-NCE-2-1-chocolatine-louis.malaval.git
jobs :
    job-name :
        name : Mirror repository
        runs-on : ubuntu-latest
        if: |
            startsWith(github.ref, 'refs/heads/ga-ignore-') == false &&
            github.repository != 'EpitechPromo2028/B-DOP-200-NCE-2-1-chocolatine-louis.malaval'
        steps :
            - uses : actions/checkout@v3
              with :
                fetch-depth : 0
            - uses : pixta-dev/repository-mirroring-action@v1
              with :
                ssh_private_key : ${{ secrets.SSH_PRIVATE_KEY }}
                target_repo_url : ${{ env.TARGET_REPO_URL }}